# Verifies building

on:
  push:
  pull_request:
    branches:
      - master
    types:
      - opened
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
          submodules: false

      - name: Install Ubuntu Dependencies
        run: |
          sudo apt install libgl-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev uuid-dev
          sudo apt install gcc-12 g++-12

      - name: Install conan
        run: python -m pip install conan
  
      - name: Add Conan Server
        run: conan remote add grc ${{ secrets.CONAN_REMOTE_URL }} --force

      - name: Clear Conan Cache
        run: conan remove "*" -f
      
      - name: Conan Install
        run: conan install . -if build -pr:h ConanProfiles/Linux-gcc-12-Debug.ini -pr:b ConanProfiles/Linux-gcc-12-Debug.ini -r grc -e CC=gcc-12 -e CXX=g++-12
      
      - name: Conan Build
        run: conan build . -if build
      
      - name: Clear Conan Cache
        run: conan remove "*" -f
      
      - run: conan remote remove grc

