# Verifies building

on:
  push:
  pull_request:
    branches:
      - master
    types:
      - opened
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
          submodules: false

      - name: Environment Variables
        run: |
          export UBUNTU_CI_BUILD=1
          export NOT_ON_C3I=1

      - name: Install conan
        run: python -m pip install conan
  
      - name: Add Conan Server
        run: conan remote add grc ${{ secrets.CONAN_REMOTE_URL }} --force

      - name: Clear Conan Cache
        run: conan remove "*" -f

      - name: Restore Conan Cache
        id: cache-conan-pkgs
        uses: actions/cache/restore@v3
        with:
          path: ~/.conan
          key: ${{ runner.os }}-${{ github.ref_name }}

      - name: Conan Install
        run: conan install . -if build -pr:h ConanProfiles/Ubuntu-gcc-11-Debug.ini -pr:b ConanProfiles/Ubuntu-gcc-11-Debug.ini -r grc -c tools.system.package_manager:mode=install -c tools.system.package_manager:tool=apt-get -c tools.system.package_manager:sudo=True
      
      - name: Save Conan Cache
        uses: actions/cache/save@v3
        with:
          path: ~/.conan
          key: ${{ runner.os }}-${{ github.ref_name }}

      - name: Get LinuxDeployQt
        run: |
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage

      - name: Conan Build
        run: conan build . -if build
      
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: UbuntuDashBuild-Debug
          path: build/Debug/bin

      - name: Clear Conan Cache
        run: conan remove "*" -f
      
      - run: conan remote remove grc

