# Verifies building

on:
  push:
  pull_request:
    branches:
      - master
    types:
      - opened
      - closed

jobs:
  build:
    env:
      NOT_ON_C3I: 1
      LINUX_X86_64_BUILD_APP_IMAGE: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
          submodules: false

      - name: Install Ubuntu Dependencies
        run: sudo apt-get install libgl-dev libxcb-util-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev uuid-dev

      - name: Install conan
        run: python -m pip install conan
  
      - name: Add Conan Server
        run: conan remote add grc ${{ secrets.CONAN_REMOTE_URL }} --force

      - name: Clear Conan Cache
        run: conan remove "*" -f

      - run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Restore Conan Cache
        id: cache-conan-pkgs
        uses: actions/cache/restore@v3
        with:
          path: ~/.conan
          key: ${{ runner.os }}-${{ github.ref_name }}-${{ env.NOW }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref_name }}-

      - name: Conan Install
        run: conan install . -if build -pr:h ConanProfiles/Ubuntu-gcc-11-Release.ini -pr:b ConanProfiles/Ubuntu-gcc-11-Release.ini -r grc
      
      - name: Save Conan Cache
        if: always()
        uses: actions/cache/save@v3
        with:
          path: ~/.conan
          key: ${{ runner.os }}-${{ github.ref_name }}-${{ env.NOW }}

      - name: Prep Linux Deploy
        run: |
          sudo apt-get install libfuse
          wget -c -nv "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage"
          wget -c -nv "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
          chmod a+x linuxdeploy-plugin-qt-x86_64.AppImage
          chmod a+x linuxdeploy-x86_64.AppImage

      - name: Conan Build
        run: conan build . -if build
      
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: UbuntuDashBuild-Debug
          path: build/Debug/bin

      - name: Clear Conan Cache
        run: conan remove "*" -f
      
      - run: conan remote remove grc

